apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/christianh814/simple-go
  roles:
  - name: custom-project-role
    description: The "custom-project-role" will be applied to "christian"
    groups:
    - christian
    policies:
    - p, proj:workloads:custom-project-role, projects, get, workloads, allow
    - p, proj:workloads:custom-project-role, applications, *, workloads/*, allow
