apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
- name: cert-manager
  version: 1.16.1
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  namespace: cert-manager
  valuesFile: values.yaml
