apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-go
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: goapps
  source:
    path: deploy/overlays/default
    repoURL: https://github.com/christianh814/simple-go
    targetRevision: main
  project: workloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
