apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  globalProjects: |-
    - labelSelector:
        matchExpressions:
          - key: env
            operator: In
            values:
              - prod
      projectName: global-prod
