apiVersion: v1
kind: Secret
metadata:
  name: bgd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/christianh814/bgd
  project: scoped
